replicaCount: 1

minio:
  image: minio/minio:RELEASE.2024-05-01T00-00-00Z
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  drivesPerNode: 1 
  storageRequest: 2Gi

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: minio.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

initJob:
  enabled: true
  bucket: "my-bucket"
  fileUrl: "https://media.giphy.com/media/VdiQKDAguhDSi37gn1/giphy.gif"
  fileName: "giphy.gif"
