apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  serviceName: {{ include "minio.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "minio.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.fullname" . }}
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.image }}
        args:
          - server
          - "--address=:9000"
          - "--console-address=:9001"
          {{- range $i := until (.Values.replicaCount | int) }}
          {{- range $j := until ($.Values.minio.drivesPerNode | int) }}
          - http://{{ include "minio.fullname" $ }}-{{ $i }}.{{ include "minio.fullname" $ }}-headless:9000/data{{ $j }}
          {{- end }}
          {{- end }}
        env:
          - name: MINIO_ROOT_USER
            value: {{ .Values.minio.accessKey }}
          - name: MINIO_ROOT_PASSWORD
            value: {{ .Values.minio.secretKey }}
        ports:
          - containerPort: 9000
          - containerPort: 9001
        volumeMounts:
          {{- range $i := until ($.Values.minio.drivesPerNode | int) }}
          - name: data{{ $i }}
            mountPath: /data{{ $i }}
          {{- end }}
      volumes: []
  volumeClaimTemplates:
    {{- range $i := until ($.Values.minio.drivesPerNode | int) }}
    - metadata:
        name: data{{ $i }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.minio.storageRequest }}
    {{- end }}
