apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "minio.fullname" . }}
  ports:
    - port: 9000
      name: api
