name: Helm Chart Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update Chart Version
        run: |
          sed -i "s/^version:.*/version: ${VERSION}/" charts/minio-distributed/Chart.yaml

      - name: Package Helm Chart
        run: |
          mkdir -p packages
          helm lint charts/minio-distributed
          helm package charts/minio-distributed --destination packages

      - name: Generate Helm Repo index
        run: |
          cd packages
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages
